
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: CI/CD POC

on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
    
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      
      - name: List files for debugging
        run: |
          ls -R

        
      

      - name: Install dependencies
        run: |
          pip install nbconvert ipykernel
      

      - name: Execute test_cases notebook
        run: |
          jupyter nbconvert --execute --inplace tests/test_cases.ipynb --ExecutePreprocessor.timeout=300
          echo "Testing is done"
      - name: Execute model training notebook
        run: |
          jupyter nbconvert --execute --inplace model_dev.ipynb --ExecutePreprocessor.timeout=300
          echo "Training is done"
      

      - name: List generated files
        run: |
          ls -lh Model_Artifacts/*.pkl || echo "No .pkl file found"
      

      - name: Upload .pkl file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: lr-model-pkl
          path: Model_Artifacts/lr_model_new.pkl




        


